//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFrontForm.SBack {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SOAPResponse", Namespace="http://amian.es/schneiderbackend")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SFrontForm.SBack.SoapListGateway))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SFrontForm.SBack.SoapListElectricityMeter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SFrontForm.SBack.SoapListWaterMeter))]
    public partial class SOAPResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MsgField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Msg {
            get {
                return this.MsgField;
            }
            set {
                if ((object.ReferenceEquals(this.MsgField, value) != true)) {
                    this.MsgField = value;
                    this.RaisePropertyChanged("Msg");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SoapListGateway", Namespace="http://amian.es/schneiderbackend")]
    [System.SerializableAttribute()]
    public partial class SoapListGateway : SFrontForm.SBack.SOAPResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SFrontForm.SBack.Gateway[] EntitiesField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public SFrontForm.SBack.Gateway[] Entities {
            get {
                return this.EntitiesField;
            }
            set {
                if ((object.ReferenceEquals(this.EntitiesField, value) != true)) {
                    this.EntitiesField = value;
                    this.RaisePropertyChanged("Entities");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SoapListElectricityMeter", Namespace="http://amian.es/schneiderbackend")]
    [System.SerializableAttribute()]
    public partial class SoapListElectricityMeter : SFrontForm.SBack.SOAPResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SFrontForm.SBack.ElectricityMeter[] EntitiesField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public SFrontForm.SBack.ElectricityMeter[] Entities {
            get {
                return this.EntitiesField;
            }
            set {
                if ((object.ReferenceEquals(this.EntitiesField, value) != true)) {
                    this.EntitiesField = value;
                    this.RaisePropertyChanged("Entities");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SoapListWaterMeter", Namespace="http://amian.es/schneiderbackend")]
    [System.SerializableAttribute()]
    public partial class SoapListWaterMeter : SFrontForm.SBack.SOAPResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SFrontForm.SBack.WaterMeter[] EntitiesField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public SFrontForm.SBack.WaterMeter[] Entities {
            get {
                return this.EntitiesField;
            }
            set {
                if ((object.ReferenceEquals(this.EntitiesField, value) != true)) {
                    this.EntitiesField = value;
                    this.RaisePropertyChanged("Entities");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Gateway", Namespace="http://amian.es/schneiderbackend")]
    [System.SerializableAttribute()]
    public partial class Gateway : SFrontForm.SBack.Entity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IpField;
        
        private System.Nullable<int> PortField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Ip {
            get {
                return this.IpField;
            }
            set {
                if ((object.ReferenceEquals(this.IpField, value) != true)) {
                    this.IpField = value;
                    this.RaisePropertyChanged("Ip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> Port {
            get {
                return this.PortField;
            }
            set {
                if ((this.PortField.Equals(value) != true)) {
                    this.PortField = value;
                    this.RaisePropertyChanged("Port");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Entity", Namespace="http://amian.es/schneiderbackend")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SFrontForm.SBack.ElectricityMeter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SFrontForm.SBack.WaterMeter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SFrontForm.SBack.Gateway))]
    public partial class Entity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<int> IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SerialNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrandField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SerialNumber {
            get {
                return this.SerialNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.SerialNumberField, value) != true)) {
                    this.SerialNumberField = value;
                    this.RaisePropertyChanged("SerialNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Brand {
            get {
                return this.BrandField;
            }
            set {
                if ((object.ReferenceEquals(this.BrandField, value) != true)) {
                    this.BrandField = value;
                    this.RaisePropertyChanged("Brand");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Model {
            get {
                return this.ModelField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelField, value) != true)) {
                    this.ModelField = value;
                    this.RaisePropertyChanged("Model");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ElectricityMeter", Namespace="http://amian.es/schneiderbackend")]
    [System.SerializableAttribute()]
    public partial class ElectricityMeter : SFrontForm.SBack.Entity {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WaterMeter", Namespace="http://amian.es/schneiderbackend")]
    [System.SerializableAttribute()]
    public partial class WaterMeter : SFrontForm.SBack.Entity {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://amian.es/schneiderbackend", ConfigurationName="SBack.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento serial del espacio de nombres http://amian.es/schneiderbackend no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://amian.es/schneiderbackend/CreateWaterMeter", ReplyAction="*")]
        SFrontForm.SBack.CreateWaterMeterResponse CreateWaterMeter(SFrontForm.SBack.CreateWaterMeterRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento serial del espacio de nombres http://amian.es/schneiderbackend no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://amian.es/schneiderbackend/CreateElectricityMeter", ReplyAction="*")]
        SFrontForm.SBack.CreateElectricityMeterResponse CreateElectricityMeter(SFrontForm.SBack.CreateElectricityMeterRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento serial del espacio de nombres http://amian.es/schneiderbackend no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://amian.es/schneiderbackend/CreateGateway", ReplyAction="*")]
        SFrontForm.SBack.CreateGatewayResponse CreateGateway(SFrontForm.SBack.CreateGatewayRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetAllGatewaysResult del espacio de nombres http://amian.es/schneiderbackend no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://amian.es/schneiderbackend/GetAllGateways", ReplyAction="*")]
        SFrontForm.SBack.GetAllGatewaysResponse GetAllGateways(SFrontForm.SBack.GetAllGatewaysRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento serial del espacio de nombres http://amian.es/schneiderbackend no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://amian.es/schneiderbackend/GetGatewayBySerial", ReplyAction="*")]
        SFrontForm.SBack.GetGatewayBySerialResponse GetGatewayBySerial(SFrontForm.SBack.GetGatewayBySerialRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento serial del espacio de nombres http://amian.es/schneiderbackend no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://amian.es/schneiderbackend/DeleteGatewayBySerial", ReplyAction="*")]
        SFrontForm.SBack.DeleteGatewayBySerialResponse DeleteGatewayBySerial(SFrontForm.SBack.DeleteGatewayBySerialRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetAllElectricityMeterResult del espacio de nombres http://amian.es/schneiderbackend no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://amian.es/schneiderbackend/GetAllElectricityMeter", ReplyAction="*")]
        SFrontForm.SBack.GetAllElectricityMeterResponse GetAllElectricityMeter(SFrontForm.SBack.GetAllElectricityMeterRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento serial del espacio de nombres http://amian.es/schneiderbackend no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://amian.es/schneiderbackend/GetElectricityMeterBySerial", ReplyAction="*")]
        SFrontForm.SBack.GetElectricityMeterBySerialResponse GetElectricityMeterBySerial(SFrontForm.SBack.GetElectricityMeterBySerialRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento serial del espacio de nombres http://amian.es/schneiderbackend no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://amian.es/schneiderbackend/DeleteElectricityMeterBySerial", ReplyAction="*")]
        SFrontForm.SBack.DeleteElectricityMeterBySerialResponse DeleteElectricityMeterBySerial(SFrontForm.SBack.DeleteElectricityMeterBySerialRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetAllWaterMeterResult del espacio de nombres http://amian.es/schneiderbackend no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://amian.es/schneiderbackend/GetAllWaterMeter", ReplyAction="*")]
        SFrontForm.SBack.GetAllWaterMeterResponse GetAllWaterMeter(SFrontForm.SBack.GetAllWaterMeterRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento serial del espacio de nombres http://amian.es/schneiderbackend no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://amian.es/schneiderbackend/GetWaterMeterBySerial", ReplyAction="*")]
        SFrontForm.SBack.GetWaterMeterBySerialResponse GetWaterMeterBySerial(SFrontForm.SBack.GetWaterMeterBySerialRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento serial del espacio de nombres http://amian.es/schneiderbackend no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://amian.es/schneiderbackend/DeleteWaterMeterBySerial", ReplyAction="*")]
        SFrontForm.SBack.DeleteWaterMeterBySerialResponse DeleteWaterMeterBySerial(SFrontForm.SBack.DeleteWaterMeterBySerialRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateWaterMeterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateWaterMeter", Namespace="http://amian.es/schneiderbackend", Order=0)]
        public SFrontForm.SBack.CreateWaterMeterRequestBody Body;
        
        public CreateWaterMeterRequest() {
        }
        
        public CreateWaterMeterRequest(SFrontForm.SBack.CreateWaterMeterRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://amian.es/schneiderbackend")]
    public partial class CreateWaterMeterRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string serial;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string brand;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string model;
        
        public CreateWaterMeterRequestBody() {
        }
        
        public CreateWaterMeterRequestBody(string serial, string brand, string model) {
            this.serial = serial;
            this.brand = brand;
            this.model = model;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateWaterMeterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateWaterMeterResponse", Namespace="http://amian.es/schneiderbackend", Order=0)]
        public SFrontForm.SBack.CreateWaterMeterResponseBody Body;
        
        public CreateWaterMeterResponse() {
        }
        
        public CreateWaterMeterResponse(SFrontForm.SBack.CreateWaterMeterResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://amian.es/schneiderbackend")]
    public partial class CreateWaterMeterResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SFrontForm.SBack.SOAPResponse CreateWaterMeterResult;
        
        public CreateWaterMeterResponseBody() {
        }
        
        public CreateWaterMeterResponseBody(SFrontForm.SBack.SOAPResponse CreateWaterMeterResult) {
            this.CreateWaterMeterResult = CreateWaterMeterResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateElectricityMeterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateElectricityMeter", Namespace="http://amian.es/schneiderbackend", Order=0)]
        public SFrontForm.SBack.CreateElectricityMeterRequestBody Body;
        
        public CreateElectricityMeterRequest() {
        }
        
        public CreateElectricityMeterRequest(SFrontForm.SBack.CreateElectricityMeterRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://amian.es/schneiderbackend")]
    public partial class CreateElectricityMeterRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string serial;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string brand;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string model;
        
        public CreateElectricityMeterRequestBody() {
        }
        
        public CreateElectricityMeterRequestBody(string serial, string brand, string model) {
            this.serial = serial;
            this.brand = brand;
            this.model = model;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateElectricityMeterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateElectricityMeterResponse", Namespace="http://amian.es/schneiderbackend", Order=0)]
        public SFrontForm.SBack.CreateElectricityMeterResponseBody Body;
        
        public CreateElectricityMeterResponse() {
        }
        
        public CreateElectricityMeterResponse(SFrontForm.SBack.CreateElectricityMeterResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://amian.es/schneiderbackend")]
    public partial class CreateElectricityMeterResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SFrontForm.SBack.SOAPResponse CreateElectricityMeterResult;
        
        public CreateElectricityMeterResponseBody() {
        }
        
        public CreateElectricityMeterResponseBody(SFrontForm.SBack.SOAPResponse CreateElectricityMeterResult) {
            this.CreateElectricityMeterResult = CreateElectricityMeterResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateGatewayRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateGateway", Namespace="http://amian.es/schneiderbackend", Order=0)]
        public SFrontForm.SBack.CreateGatewayRequestBody Body;
        
        public CreateGatewayRequest() {
        }
        
        public CreateGatewayRequest(SFrontForm.SBack.CreateGatewayRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://amian.es/schneiderbackend")]
    public partial class CreateGatewayRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string serial;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string brand;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string model;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ip;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string port;
        
        public CreateGatewayRequestBody() {
        }
        
        public CreateGatewayRequestBody(string serial, string brand, string model, string ip, string port) {
            this.serial = serial;
            this.brand = brand;
            this.model = model;
            this.ip = ip;
            this.port = port;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateGatewayResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateGatewayResponse", Namespace="http://amian.es/schneiderbackend", Order=0)]
        public SFrontForm.SBack.CreateGatewayResponseBody Body;
        
        public CreateGatewayResponse() {
        }
        
        public CreateGatewayResponse(SFrontForm.SBack.CreateGatewayResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://amian.es/schneiderbackend")]
    public partial class CreateGatewayResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SFrontForm.SBack.SOAPResponse CreateGatewayResult;
        
        public CreateGatewayResponseBody() {
        }
        
        public CreateGatewayResponseBody(SFrontForm.SBack.SOAPResponse CreateGatewayResult) {
            this.CreateGatewayResult = CreateGatewayResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllGatewaysRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllGateways", Namespace="http://amian.es/schneiderbackend", Order=0)]
        public SFrontForm.SBack.GetAllGatewaysRequestBody Body;
        
        public GetAllGatewaysRequest() {
        }
        
        public GetAllGatewaysRequest(SFrontForm.SBack.GetAllGatewaysRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllGatewaysRequestBody {
        
        public GetAllGatewaysRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllGatewaysResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllGatewaysResponse", Namespace="http://amian.es/schneiderbackend", Order=0)]
        public SFrontForm.SBack.GetAllGatewaysResponseBody Body;
        
        public GetAllGatewaysResponse() {
        }
        
        public GetAllGatewaysResponse(SFrontForm.SBack.GetAllGatewaysResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://amian.es/schneiderbackend")]
    public partial class GetAllGatewaysResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SFrontForm.SBack.SoapListGateway GetAllGatewaysResult;
        
        public GetAllGatewaysResponseBody() {
        }
        
        public GetAllGatewaysResponseBody(SFrontForm.SBack.SoapListGateway GetAllGatewaysResult) {
            this.GetAllGatewaysResult = GetAllGatewaysResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGatewayBySerialRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGatewayBySerial", Namespace="http://amian.es/schneiderbackend", Order=0)]
        public SFrontForm.SBack.GetGatewayBySerialRequestBody Body;
        
        public GetGatewayBySerialRequest() {
        }
        
        public GetGatewayBySerialRequest(SFrontForm.SBack.GetGatewayBySerialRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://amian.es/schneiderbackend")]
    public partial class GetGatewayBySerialRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string serial;
        
        public GetGatewayBySerialRequestBody() {
        }
        
        public GetGatewayBySerialRequestBody(string serial) {
            this.serial = serial;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGatewayBySerialResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGatewayBySerialResponse", Namespace="http://amian.es/schneiderbackend", Order=0)]
        public SFrontForm.SBack.GetGatewayBySerialResponseBody Body;
        
        public GetGatewayBySerialResponse() {
        }
        
        public GetGatewayBySerialResponse(SFrontForm.SBack.GetGatewayBySerialResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://amian.es/schneiderbackend")]
    public partial class GetGatewayBySerialResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SFrontForm.SBack.SoapListGateway GetGatewayBySerialResult;
        
        public GetGatewayBySerialResponseBody() {
        }
        
        public GetGatewayBySerialResponseBody(SFrontForm.SBack.SoapListGateway GetGatewayBySerialResult) {
            this.GetGatewayBySerialResult = GetGatewayBySerialResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteGatewayBySerialRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteGatewayBySerial", Namespace="http://amian.es/schneiderbackend", Order=0)]
        public SFrontForm.SBack.DeleteGatewayBySerialRequestBody Body;
        
        public DeleteGatewayBySerialRequest() {
        }
        
        public DeleteGatewayBySerialRequest(SFrontForm.SBack.DeleteGatewayBySerialRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://amian.es/schneiderbackend")]
    public partial class DeleteGatewayBySerialRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string serial;
        
        public DeleteGatewayBySerialRequestBody() {
        }
        
        public DeleteGatewayBySerialRequestBody(string serial) {
            this.serial = serial;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteGatewayBySerialResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteGatewayBySerialResponse", Namespace="http://amian.es/schneiderbackend", Order=0)]
        public SFrontForm.SBack.DeleteGatewayBySerialResponseBody Body;
        
        public DeleteGatewayBySerialResponse() {
        }
        
        public DeleteGatewayBySerialResponse(SFrontForm.SBack.DeleteGatewayBySerialResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://amian.es/schneiderbackend")]
    public partial class DeleteGatewayBySerialResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SFrontForm.SBack.SOAPResponse DeleteGatewayBySerialResult;
        
        public DeleteGatewayBySerialResponseBody() {
        }
        
        public DeleteGatewayBySerialResponseBody(SFrontForm.SBack.SOAPResponse DeleteGatewayBySerialResult) {
            this.DeleteGatewayBySerialResult = DeleteGatewayBySerialResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllElectricityMeterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllElectricityMeter", Namespace="http://amian.es/schneiderbackend", Order=0)]
        public SFrontForm.SBack.GetAllElectricityMeterRequestBody Body;
        
        public GetAllElectricityMeterRequest() {
        }
        
        public GetAllElectricityMeterRequest(SFrontForm.SBack.GetAllElectricityMeterRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllElectricityMeterRequestBody {
        
        public GetAllElectricityMeterRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllElectricityMeterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllElectricityMeterResponse", Namespace="http://amian.es/schneiderbackend", Order=0)]
        public SFrontForm.SBack.GetAllElectricityMeterResponseBody Body;
        
        public GetAllElectricityMeterResponse() {
        }
        
        public GetAllElectricityMeterResponse(SFrontForm.SBack.GetAllElectricityMeterResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://amian.es/schneiderbackend")]
    public partial class GetAllElectricityMeterResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SFrontForm.SBack.SoapListElectricityMeter GetAllElectricityMeterResult;
        
        public GetAllElectricityMeterResponseBody() {
        }
        
        public GetAllElectricityMeterResponseBody(SFrontForm.SBack.SoapListElectricityMeter GetAllElectricityMeterResult) {
            this.GetAllElectricityMeterResult = GetAllElectricityMeterResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetElectricityMeterBySerialRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetElectricityMeterBySerial", Namespace="http://amian.es/schneiderbackend", Order=0)]
        public SFrontForm.SBack.GetElectricityMeterBySerialRequestBody Body;
        
        public GetElectricityMeterBySerialRequest() {
        }
        
        public GetElectricityMeterBySerialRequest(SFrontForm.SBack.GetElectricityMeterBySerialRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://amian.es/schneiderbackend")]
    public partial class GetElectricityMeterBySerialRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string serial;
        
        public GetElectricityMeterBySerialRequestBody() {
        }
        
        public GetElectricityMeterBySerialRequestBody(string serial) {
            this.serial = serial;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetElectricityMeterBySerialResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetElectricityMeterBySerialResponse", Namespace="http://amian.es/schneiderbackend", Order=0)]
        public SFrontForm.SBack.GetElectricityMeterBySerialResponseBody Body;
        
        public GetElectricityMeterBySerialResponse() {
        }
        
        public GetElectricityMeterBySerialResponse(SFrontForm.SBack.GetElectricityMeterBySerialResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://amian.es/schneiderbackend")]
    public partial class GetElectricityMeterBySerialResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SFrontForm.SBack.SoapListElectricityMeter GetElectricityMeterBySerialResult;
        
        public GetElectricityMeterBySerialResponseBody() {
        }
        
        public GetElectricityMeterBySerialResponseBody(SFrontForm.SBack.SoapListElectricityMeter GetElectricityMeterBySerialResult) {
            this.GetElectricityMeterBySerialResult = GetElectricityMeterBySerialResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteElectricityMeterBySerialRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteElectricityMeterBySerial", Namespace="http://amian.es/schneiderbackend", Order=0)]
        public SFrontForm.SBack.DeleteElectricityMeterBySerialRequestBody Body;
        
        public DeleteElectricityMeterBySerialRequest() {
        }
        
        public DeleteElectricityMeterBySerialRequest(SFrontForm.SBack.DeleteElectricityMeterBySerialRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://amian.es/schneiderbackend")]
    public partial class DeleteElectricityMeterBySerialRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string serial;
        
        public DeleteElectricityMeterBySerialRequestBody() {
        }
        
        public DeleteElectricityMeterBySerialRequestBody(string serial) {
            this.serial = serial;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteElectricityMeterBySerialResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteElectricityMeterBySerialResponse", Namespace="http://amian.es/schneiderbackend", Order=0)]
        public SFrontForm.SBack.DeleteElectricityMeterBySerialResponseBody Body;
        
        public DeleteElectricityMeterBySerialResponse() {
        }
        
        public DeleteElectricityMeterBySerialResponse(SFrontForm.SBack.DeleteElectricityMeterBySerialResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://amian.es/schneiderbackend")]
    public partial class DeleteElectricityMeterBySerialResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SFrontForm.SBack.SOAPResponse DeleteElectricityMeterBySerialResult;
        
        public DeleteElectricityMeterBySerialResponseBody() {
        }
        
        public DeleteElectricityMeterBySerialResponseBody(SFrontForm.SBack.SOAPResponse DeleteElectricityMeterBySerialResult) {
            this.DeleteElectricityMeterBySerialResult = DeleteElectricityMeterBySerialResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllWaterMeterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllWaterMeter", Namespace="http://amian.es/schneiderbackend", Order=0)]
        public SFrontForm.SBack.GetAllWaterMeterRequestBody Body;
        
        public GetAllWaterMeterRequest() {
        }
        
        public GetAllWaterMeterRequest(SFrontForm.SBack.GetAllWaterMeterRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllWaterMeterRequestBody {
        
        public GetAllWaterMeterRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllWaterMeterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllWaterMeterResponse", Namespace="http://amian.es/schneiderbackend", Order=0)]
        public SFrontForm.SBack.GetAllWaterMeterResponseBody Body;
        
        public GetAllWaterMeterResponse() {
        }
        
        public GetAllWaterMeterResponse(SFrontForm.SBack.GetAllWaterMeterResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://amian.es/schneiderbackend")]
    public partial class GetAllWaterMeterResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SFrontForm.SBack.SoapListWaterMeter GetAllWaterMeterResult;
        
        public GetAllWaterMeterResponseBody() {
        }
        
        public GetAllWaterMeterResponseBody(SFrontForm.SBack.SoapListWaterMeter GetAllWaterMeterResult) {
            this.GetAllWaterMeterResult = GetAllWaterMeterResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWaterMeterBySerialRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWaterMeterBySerial", Namespace="http://amian.es/schneiderbackend", Order=0)]
        public SFrontForm.SBack.GetWaterMeterBySerialRequestBody Body;
        
        public GetWaterMeterBySerialRequest() {
        }
        
        public GetWaterMeterBySerialRequest(SFrontForm.SBack.GetWaterMeterBySerialRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://amian.es/schneiderbackend")]
    public partial class GetWaterMeterBySerialRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string serial;
        
        public GetWaterMeterBySerialRequestBody() {
        }
        
        public GetWaterMeterBySerialRequestBody(string serial) {
            this.serial = serial;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWaterMeterBySerialResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWaterMeterBySerialResponse", Namespace="http://amian.es/schneiderbackend", Order=0)]
        public SFrontForm.SBack.GetWaterMeterBySerialResponseBody Body;
        
        public GetWaterMeterBySerialResponse() {
        }
        
        public GetWaterMeterBySerialResponse(SFrontForm.SBack.GetWaterMeterBySerialResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://amian.es/schneiderbackend")]
    public partial class GetWaterMeterBySerialResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SFrontForm.SBack.SoapListWaterMeter GetWaterMeterBySerialResult;
        
        public GetWaterMeterBySerialResponseBody() {
        }
        
        public GetWaterMeterBySerialResponseBody(SFrontForm.SBack.SoapListWaterMeter GetWaterMeterBySerialResult) {
            this.GetWaterMeterBySerialResult = GetWaterMeterBySerialResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteWaterMeterBySerialRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteWaterMeterBySerial", Namespace="http://amian.es/schneiderbackend", Order=0)]
        public SFrontForm.SBack.DeleteWaterMeterBySerialRequestBody Body;
        
        public DeleteWaterMeterBySerialRequest() {
        }
        
        public DeleteWaterMeterBySerialRequest(SFrontForm.SBack.DeleteWaterMeterBySerialRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://amian.es/schneiderbackend")]
    public partial class DeleteWaterMeterBySerialRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string serial;
        
        public DeleteWaterMeterBySerialRequestBody() {
        }
        
        public DeleteWaterMeterBySerialRequestBody(string serial) {
            this.serial = serial;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteWaterMeterBySerialResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteWaterMeterBySerialResponse", Namespace="http://amian.es/schneiderbackend", Order=0)]
        public SFrontForm.SBack.DeleteWaterMeterBySerialResponseBody Body;
        
        public DeleteWaterMeterBySerialResponse() {
        }
        
        public DeleteWaterMeterBySerialResponse(SFrontForm.SBack.DeleteWaterMeterBySerialResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://amian.es/schneiderbackend")]
    public partial class DeleteWaterMeterBySerialResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SFrontForm.SBack.SOAPResponse DeleteWaterMeterBySerialResult;
        
        public DeleteWaterMeterBySerialResponseBody() {
        }
        
        public DeleteWaterMeterBySerialResponseBody(SFrontForm.SBack.SOAPResponse DeleteWaterMeterBySerialResult) {
            this.DeleteWaterMeterBySerialResult = DeleteWaterMeterBySerialResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : SFrontForm.SBack.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<SFrontForm.SBack.ServiceSoap>, SFrontForm.SBack.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SFrontForm.SBack.CreateWaterMeterResponse SFrontForm.SBack.ServiceSoap.CreateWaterMeter(SFrontForm.SBack.CreateWaterMeterRequest request) {
            return base.Channel.CreateWaterMeter(request);
        }
        
        public SFrontForm.SBack.SOAPResponse CreateWaterMeter(string serial, string brand, string model) {
            SFrontForm.SBack.CreateWaterMeterRequest inValue = new SFrontForm.SBack.CreateWaterMeterRequest();
            inValue.Body = new SFrontForm.SBack.CreateWaterMeterRequestBody();
            inValue.Body.serial = serial;
            inValue.Body.brand = brand;
            inValue.Body.model = model;
            SFrontForm.SBack.CreateWaterMeterResponse retVal = ((SFrontForm.SBack.ServiceSoap)(this)).CreateWaterMeter(inValue);
            return retVal.Body.CreateWaterMeterResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SFrontForm.SBack.CreateElectricityMeterResponse SFrontForm.SBack.ServiceSoap.CreateElectricityMeter(SFrontForm.SBack.CreateElectricityMeterRequest request) {
            return base.Channel.CreateElectricityMeter(request);
        }
        
        public SFrontForm.SBack.SOAPResponse CreateElectricityMeter(string serial, string brand, string model) {
            SFrontForm.SBack.CreateElectricityMeterRequest inValue = new SFrontForm.SBack.CreateElectricityMeterRequest();
            inValue.Body = new SFrontForm.SBack.CreateElectricityMeterRequestBody();
            inValue.Body.serial = serial;
            inValue.Body.brand = brand;
            inValue.Body.model = model;
            SFrontForm.SBack.CreateElectricityMeterResponse retVal = ((SFrontForm.SBack.ServiceSoap)(this)).CreateElectricityMeter(inValue);
            return retVal.Body.CreateElectricityMeterResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SFrontForm.SBack.CreateGatewayResponse SFrontForm.SBack.ServiceSoap.CreateGateway(SFrontForm.SBack.CreateGatewayRequest request) {
            return base.Channel.CreateGateway(request);
        }
        
        public SFrontForm.SBack.SOAPResponse CreateGateway(string serial, string brand, string model, string ip, string port) {
            SFrontForm.SBack.CreateGatewayRequest inValue = new SFrontForm.SBack.CreateGatewayRequest();
            inValue.Body = new SFrontForm.SBack.CreateGatewayRequestBody();
            inValue.Body.serial = serial;
            inValue.Body.brand = brand;
            inValue.Body.model = model;
            inValue.Body.ip = ip;
            inValue.Body.port = port;
            SFrontForm.SBack.CreateGatewayResponse retVal = ((SFrontForm.SBack.ServiceSoap)(this)).CreateGateway(inValue);
            return retVal.Body.CreateGatewayResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SFrontForm.SBack.GetAllGatewaysResponse SFrontForm.SBack.ServiceSoap.GetAllGateways(SFrontForm.SBack.GetAllGatewaysRequest request) {
            return base.Channel.GetAllGateways(request);
        }
        
        public SFrontForm.SBack.SoapListGateway GetAllGateways() {
            SFrontForm.SBack.GetAllGatewaysRequest inValue = new SFrontForm.SBack.GetAllGatewaysRequest();
            inValue.Body = new SFrontForm.SBack.GetAllGatewaysRequestBody();
            SFrontForm.SBack.GetAllGatewaysResponse retVal = ((SFrontForm.SBack.ServiceSoap)(this)).GetAllGateways(inValue);
            return retVal.Body.GetAllGatewaysResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SFrontForm.SBack.GetGatewayBySerialResponse SFrontForm.SBack.ServiceSoap.GetGatewayBySerial(SFrontForm.SBack.GetGatewayBySerialRequest request) {
            return base.Channel.GetGatewayBySerial(request);
        }
        
        public SFrontForm.SBack.SoapListGateway GetGatewayBySerial(string serial) {
            SFrontForm.SBack.GetGatewayBySerialRequest inValue = new SFrontForm.SBack.GetGatewayBySerialRequest();
            inValue.Body = new SFrontForm.SBack.GetGatewayBySerialRequestBody();
            inValue.Body.serial = serial;
            SFrontForm.SBack.GetGatewayBySerialResponse retVal = ((SFrontForm.SBack.ServiceSoap)(this)).GetGatewayBySerial(inValue);
            return retVal.Body.GetGatewayBySerialResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SFrontForm.SBack.DeleteGatewayBySerialResponse SFrontForm.SBack.ServiceSoap.DeleteGatewayBySerial(SFrontForm.SBack.DeleteGatewayBySerialRequest request) {
            return base.Channel.DeleteGatewayBySerial(request);
        }
        
        public SFrontForm.SBack.SOAPResponse DeleteGatewayBySerial(string serial) {
            SFrontForm.SBack.DeleteGatewayBySerialRequest inValue = new SFrontForm.SBack.DeleteGatewayBySerialRequest();
            inValue.Body = new SFrontForm.SBack.DeleteGatewayBySerialRequestBody();
            inValue.Body.serial = serial;
            SFrontForm.SBack.DeleteGatewayBySerialResponse retVal = ((SFrontForm.SBack.ServiceSoap)(this)).DeleteGatewayBySerial(inValue);
            return retVal.Body.DeleteGatewayBySerialResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SFrontForm.SBack.GetAllElectricityMeterResponse SFrontForm.SBack.ServiceSoap.GetAllElectricityMeter(SFrontForm.SBack.GetAllElectricityMeterRequest request) {
            return base.Channel.GetAllElectricityMeter(request);
        }
        
        public SFrontForm.SBack.SoapListElectricityMeter GetAllElectricityMeter() {
            SFrontForm.SBack.GetAllElectricityMeterRequest inValue = new SFrontForm.SBack.GetAllElectricityMeterRequest();
            inValue.Body = new SFrontForm.SBack.GetAllElectricityMeterRequestBody();
            SFrontForm.SBack.GetAllElectricityMeterResponse retVal = ((SFrontForm.SBack.ServiceSoap)(this)).GetAllElectricityMeter(inValue);
            return retVal.Body.GetAllElectricityMeterResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SFrontForm.SBack.GetElectricityMeterBySerialResponse SFrontForm.SBack.ServiceSoap.GetElectricityMeterBySerial(SFrontForm.SBack.GetElectricityMeterBySerialRequest request) {
            return base.Channel.GetElectricityMeterBySerial(request);
        }
        
        public SFrontForm.SBack.SoapListElectricityMeter GetElectricityMeterBySerial(string serial) {
            SFrontForm.SBack.GetElectricityMeterBySerialRequest inValue = new SFrontForm.SBack.GetElectricityMeterBySerialRequest();
            inValue.Body = new SFrontForm.SBack.GetElectricityMeterBySerialRequestBody();
            inValue.Body.serial = serial;
            SFrontForm.SBack.GetElectricityMeterBySerialResponse retVal = ((SFrontForm.SBack.ServiceSoap)(this)).GetElectricityMeterBySerial(inValue);
            return retVal.Body.GetElectricityMeterBySerialResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SFrontForm.SBack.DeleteElectricityMeterBySerialResponse SFrontForm.SBack.ServiceSoap.DeleteElectricityMeterBySerial(SFrontForm.SBack.DeleteElectricityMeterBySerialRequest request) {
            return base.Channel.DeleteElectricityMeterBySerial(request);
        }
        
        public SFrontForm.SBack.SOAPResponse DeleteElectricityMeterBySerial(string serial) {
            SFrontForm.SBack.DeleteElectricityMeterBySerialRequest inValue = new SFrontForm.SBack.DeleteElectricityMeterBySerialRequest();
            inValue.Body = new SFrontForm.SBack.DeleteElectricityMeterBySerialRequestBody();
            inValue.Body.serial = serial;
            SFrontForm.SBack.DeleteElectricityMeterBySerialResponse retVal = ((SFrontForm.SBack.ServiceSoap)(this)).DeleteElectricityMeterBySerial(inValue);
            return retVal.Body.DeleteElectricityMeterBySerialResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SFrontForm.SBack.GetAllWaterMeterResponse SFrontForm.SBack.ServiceSoap.GetAllWaterMeter(SFrontForm.SBack.GetAllWaterMeterRequest request) {
            return base.Channel.GetAllWaterMeter(request);
        }
        
        public SFrontForm.SBack.SoapListWaterMeter GetAllWaterMeter() {
            SFrontForm.SBack.GetAllWaterMeterRequest inValue = new SFrontForm.SBack.GetAllWaterMeterRequest();
            inValue.Body = new SFrontForm.SBack.GetAllWaterMeterRequestBody();
            SFrontForm.SBack.GetAllWaterMeterResponse retVal = ((SFrontForm.SBack.ServiceSoap)(this)).GetAllWaterMeter(inValue);
            return retVal.Body.GetAllWaterMeterResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SFrontForm.SBack.GetWaterMeterBySerialResponse SFrontForm.SBack.ServiceSoap.GetWaterMeterBySerial(SFrontForm.SBack.GetWaterMeterBySerialRequest request) {
            return base.Channel.GetWaterMeterBySerial(request);
        }
        
        public SFrontForm.SBack.SoapListWaterMeter GetWaterMeterBySerial(string serial) {
            SFrontForm.SBack.GetWaterMeterBySerialRequest inValue = new SFrontForm.SBack.GetWaterMeterBySerialRequest();
            inValue.Body = new SFrontForm.SBack.GetWaterMeterBySerialRequestBody();
            inValue.Body.serial = serial;
            SFrontForm.SBack.GetWaterMeterBySerialResponse retVal = ((SFrontForm.SBack.ServiceSoap)(this)).GetWaterMeterBySerial(inValue);
            return retVal.Body.GetWaterMeterBySerialResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SFrontForm.SBack.DeleteWaterMeterBySerialResponse SFrontForm.SBack.ServiceSoap.DeleteWaterMeterBySerial(SFrontForm.SBack.DeleteWaterMeterBySerialRequest request) {
            return base.Channel.DeleteWaterMeterBySerial(request);
        }
        
        public SFrontForm.SBack.SOAPResponse DeleteWaterMeterBySerial(string serial) {
            SFrontForm.SBack.DeleteWaterMeterBySerialRequest inValue = new SFrontForm.SBack.DeleteWaterMeterBySerialRequest();
            inValue.Body = new SFrontForm.SBack.DeleteWaterMeterBySerialRequestBody();
            inValue.Body.serial = serial;
            SFrontForm.SBack.DeleteWaterMeterBySerialResponse retVal = ((SFrontForm.SBack.ServiceSoap)(this)).DeleteWaterMeterBySerial(inValue);
            return retVal.Body.DeleteWaterMeterBySerialResult;
        }
    }
}
